name: Lean Action CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Lean toolchain
        uses: leanprover/lean-action@v1
        with:
          toolchain: leanprover/lean4:v4.24.0-rc1
          auto-cache: true
      - name: Resolve deps
        run: lake update
      - name: Get mathlib cache
        run: lake exe cache get
      - name: Build
        run: lake build