name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1

      - name: Resolve deps
        run: lake update

      - name: Get mathlib cache
        run: lake exe cache get || true

      - name: Build
        run: lake build